name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Thank you for creating your first issue! We appreciate your contribution. Our team will review it and get back to you shortly."
          pr-message: "🎉 Thank you for submitting your first pull request! Your effort in contributing to our project is greatly valued. We will review your PR soon."
